NAMES_DICT: dict[str, str] = {
    'SEL_MONTHLY_NAME': 'Mean monthly subsistence expenditure line (cost of meeting basic needs)',
    'CTP_MONTHLY_NAME': 'Mean monthly capacity to pay for health care',
    'SHARE_HH_WITH_OOP_TOTAL_NAME': 'Share of households with out-of-pocket payments for health care (total)',
    'SHARE_HH_NO_OOP_TOTAL_NAME': 'Share of households without out-of-pocket payments for health care (total)',
    'SHARE_HH_WITH_OOP_QUINTILE_NAME': 'Share of households with out-of-pocket payments for health care (by consumption quintile)',
    'SHARE_HH_NO_OOP_QUINTILE_NAME': 'Share of households without out-of-pocket payments for health care (by consumption quintile)',
    'GGHED_CHE_NAME': 'Public spending on health as a share of current spending on health',
    'VHI_CHE_NAME': 'Voluntary health insurance spending as a share of current spending on health',
    'OOP_CHE_NAME': 'Out-of-pocket payments as a share of current spending on health (oop)',
    'OTHER_CHE_NAME': 'Other spending as a share of current spending on health',
    'POVERTY_LINE_OLD_NAME': 'Percent below subsistence expenditure line',
    'CATA_HEALTHCARE_TOTAL_NAME': 'Breakdown of catastrophic health spending by type of health care (total)',
    'CATA_QUINTILE_NAME': 'Share of households with catastrophic health spending by consumption quintile',
    'CATA_TOTAL_NAME': 'Share of households with catastrophic health spending (total)',
    'FURTHERIMPOV_CATA_NAME': 'Share of households with catastrophic health spending who are further impoverished',
    'IMPOV_CATA_NAME': 'Share of households with catastrophic health spending who are impoverished',
    'GGHED_GGE_NAME': 'Public spending on health as a share of government spending',
    'UN_EUSILC_DENTAL_QUINTILE_NAME': 'Self-reported unmet need for dental care due to cost, distance and waiting time (quintile)'
}
COUNTRY_DICT = {
    'BIH': 'Bosnia and Herzegovina',
    'CZH': 'Czech Republic',
    'DEU': 'Federal Republic of Germany',
    'FRA': 'French Republic',
    'GEO': 'Georgia',
    'LUX': 'Grand Duchy of Luxembourg',
    'GRC': 'Hellenic Republic',
    'HUN': 'Hungary',
    'IRL': 'Ireland',
    'BEL': 'Kingdom of Belgium',
    'DNK': 'Kingdom of Denmark',
    'NOR': 'Kingdom of Norway',
    'SPA': 'Kingdom of Spain',
    'SWE': 'Kingdom of Sweden',
    'NLD': 'Kingdom of the Netherlands',
    'KGZ': 'Kyrgyz Republic',
    'MNE': 'Montenegro',
    'POR': 'Portuguese Republic',
    'AND': 'Principality of Andorra',
    'MCO': 'Principality of Monaco',
    'ALB': 'Republic of Albania',
    'ARM': 'Republic of Armenia',
    'AUT': 'Republic of Austria',
    'AZE': 'Republic of Azerbaijan',
    'BLR': 'Republic of Belarus',
    'BUL': 'Republic of Bulgaria',
    'CRO': 'Republic of Croatia',
    'CYP': 'Republic of Cyprus',
    'EST': 'Republic of Estonia',
    'FIN': 'Republic of Finland',
    'ICE': 'Republic of Iceland',
    'ITA': 'Republic of Italy',
    'KAZ': 'Republic of Kazakhstan',
    'LVA': 'Republic of Latvia',
    'LTU': 'Republic of Lithuania',
    'MAT': 'Republic of Malta',
    'MDA': 'Republic of Moldova',
    'MKD': 'Republic of North Macedonia',
    'POL': 'Republic of Poland',
    'SMR': 'Republic of San Marino',
    'SRB': 'Republic of Serbia',
    'SVN': 'Republic of Slovenia',
    'TJK': 'Republic of Tajikistan',
    'TUR': 'Republic of Türkiye',
    'UZB': 'Republic of Uzbekistan',
    'ROU': 'Romania',
    'RUS': 'Russian Federation',
    'SVK': 'Slovak Republic',
    'ISR': 'State of Israel',
    'SWI': 'Swiss Confederation',
    'TKM': 'Turkmenistan',
    'UKR': 'Ukraine',
    'UNK': 'United Kingdom of Great Britain and Northern Ireland',
}

COMBO_LIST = [
    'Total, Outpatient care',
    'Poorest, Dental care',
    'Medical products, Richest',
    '2nd',
    '3rd',
    'Poorest, Outpatient care',
    'Dental care, 4th',
    'Diagnostic tests, 3rd',
    'Diagnostic tests, Poorest',
    'Medical products, 3rd',
    'Medical products, Poorest',
    '2nd, Outpatient care',
    'Medicines, 3rd',
    'Inpatient care',
    'Outpatient care, 3rd',
    'default',
    'Medical products, Total',
    'Dental care',
    'Richest, Dental care',
    'Richest, Outpatient care',
    'Richest',
    'Inpatient care, 4th',
    'Dental care, 2nd',
    'Diagnostic tests, Richest',
    'Medicines, 4th',
    '2nd, Medicines',
    'Inpatient care, 3rd',
    'Total, Medicines',
    'Inpatient care, Total',
    'Dental care, Total',
    'Medical products, 2nd',
    'Medical products',
    'Poorest',
    'Diagnostic tests, 4th',
    'Outpatient care',
    'Dental care, 3rd',
    'Total',
    'Richest, Inpatient care',
    'Medicines',
    'Medical products, 4th',
    'Diagnostic tests',
    'Diagnostic tests, 2nd',
    'Inpatient care, 2nd',
    '4th',
    'Richest, Medicines',
    'Poorest, Medicines',
    'Diagnostic tests, Total',
    'Poorest, Inpatient care',
    'Outpatient care, 4th'
]

OLD_NAMES_DICT = {
    'Mean annual per capita OOP by structure (by quintile)': {
        'Medicines': 'Annual out-of-pocket payments for outpatient medicines per person by consumption quintile',
        'Inpatient care': 'Annual out-of-pocket payments for inpatient care per person by consumption quintile',
        'Dental care': 'Annual out-of-pocket payments for dental care person by consumption quintile',
        'Outpatient care': 'Annual out-of-pocket payments for outpatient care per person by consumption quintile',
        'Diagnostic tests': 'Annual out-of-pocket payments for diagnostic tests per person by consumption quintile',
        'Medical products': 'Annual out-of-pocket payments for medical products per person by consumption quintile',
    },
    'Catastrophic out-of-pocket payments (total)': {
        'NA': NAMES_DICT["CATA_TOTAL_NAME"],
        'Medicines': NAMES_DICT["CATA_HEALTHCARE_TOTAL_NAME"],
        'Inpatient care': NAMES_DICT["CATA_HEALTHCARE_TOTAL_NAME"],
        'Dental care': NAMES_DICT["CATA_HEALTHCARE_TOTAL_NAME"],
        'Outpatient care': NAMES_DICT["CATA_HEALTHCARE_TOTAL_NAME"],
        'Diagnostic tests': NAMES_DICT["CATA_HEALTHCARE_TOTAL_NAME"],
        'Medical products': NAMES_DICT["CATA_HEALTHCARE_TOTAL_NAME"],
    },
    'Catastrophic out-of-pocket payments (by qunitile)': {
        'NA': NAMES_DICT["CATA_QUINTILE_NAME"],
        'Medicines': 'Breakdown of catastrophic health spending by type of health care (by consumption quintile)',
        'Inpatient care': 'Breakdown of catastrophic health spending by type of health care (by consumption quintile)',
        'Dental care': 'Breakdown of catastrophic health spending by type of health care (by consumption quintile)',
        'Outpatient care': 'Breakdown of catastrophic health spending by type of health care (by consumption quintile)',
        'Diagnostic tests': 'Breakdown of catastrophic health spending by type of health care (by consumption quintile)',
        'Medical products': 'Breakdown of catastrophic health spending by type of health care (by consumption quintile)',
    },
    'Mean annual per capita OOP by structure (total)': 'Annual out-of-pocket payments on health care per person by type of health care (total)',
    'At risk of impoverishment (all households)': 'Share of households at risk of impoverishment (all households)',
    'further impoverished (all households)': 'Share of further impoverished households (total)',
    'Impoverished (all households)': 'Share of Impoverished households (all households)',
    'Impoverishing health spending': 'Share of households with impoverishing health spending',
    'At risk of impoverishment (catastrophic households)': 'Share of households with catastrophic health spending who at risk of impoverishment',
    'further impoverished (catastrophic households)': NAMES_DICT["FURTHERIMPOV_CATA_NAME"],
    'Impoverished (catastrophic households)': NAMES_DICT["IMPOV_CATA_NAME"],
    'Not at risk of impoverishment (catastrophic households)': 'Share of households with catastrophic health spending who are not at risk of impoverishment',
    'Out-of-pocket payments as a share of total household spending among households with catastrophic spending (by quintile)': 'Out-of-pocket payments as a share of total household spending among households with catastrophic health spending by consumption quintile',
    'Average out-of-pocket payments as a share of total household spending among further impoverished households': 'Out-of-pocket payments as a share of total household spending among further impoverished households',
    'Mean annual capacity to pay': NAMES_DICT["CTP_MONTHLY_NAME"],
    NAMES_DICT["POVERTY_LINE_OLD_NAME"]: 'Percent below subsistence expenditure line (basic needs line)',
    'Mean annual subsistence expenditure line': NAMES_DICT["SEL_MONTHLY_NAME"],
    'Share of households without out-of-pocket payments (by quintile)': NAMES_DICT["SHARE_HH_NO_OOP_QUINTILE_NAME"],
    'Share of households without out-of-pocket payments (total)': NAMES_DICT["SHARE_HH_NO_OOP_TOTAL_NAME"],
    'Share of households with out-of-pocket payments (by quintile)': NAMES_DICT["SHARE_HH_WITH_OOP_QUINTILE_NAME"],
    'Share of households with out-of-pocket payments (total)': NAMES_DICT["SHARE_HH_WITH_OOP_TOTAL_NAME"],
    'Mean annual per capita OOP (by quintile)': 'Annual out-of-pocket payments for health care per person (by consumption quintile)',
    'Mean annual per capita OOP (total)': 'Annual out-of-pocket payments for health care per person (total)',
    'Out-of-pocket payments for health care as a share of household consumption (by quintile)': 'Out-of-pocket payments for health care as a share of household consumption (by consumption quintile)',
    'Share of total OOP by structure (total population)': 'Breakdown of out-of-pocket payments by type of health care (total)',
    'Share of OOP by structure (by quintile)': 'Breakdown of out-of-pocket payments by type of health care (by consumption quintile)',
}

INDICATOR_IGNORING_SERVICE = [
    'Annual out-of-pocket payments for outpatient medicines per person by consumption quintile',
    'Annual out-of-pocket payments for inpatient care per person by consumption quintile',
    'Annual out-of-pocket payments for dental care person by consumption quintile',
    'Annual out-of-pocket payments for outpatient care per person by consumption quintile',
    'Annual out-of-pocket payments for diagnostic tests per person by consumption quintile',
    'Annual out-of-pocket payments for medical products per person by consumption quintile',
]

INDICATOR_IGNORING_QUINTILE = [
    NAMES_DICT["CATA_HEALTHCARE_TOTAL_NAME"],
    'Public spending on health as a share of current spending on health by type of care',
    'Annual out-of-pocket payments on health care per person by type of health care (total)',
    'Out-of-pocket payments as a share of current spending on health by type of care',
    'Breakdown of out-of-pocket payments by type of health care (total)',
    'Voluntary health insurance spending as a share of current spending on health by type of care',
]
